// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://labzxhoshhzfixlzccrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhYnp4aG9zaGh6Zml4bHpjY3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzA0MzksImV4cCI6MjA2MDQ0NjQzOX0.GbnzLqFktcNHynfhUIHa0kf-FQyrX2wCu7p2k1uJLI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);